/* XPM */
static char *dtk_speak[] = {
/* width height num_colors chars_per_pixel */
"   100    75        8            1",
/* colors */
". c #000000",
"# c #000080",
"a c #008080",
"b c #808080",
"c c #ffff00",
"d c #ff00ff",
"e c #00ffff",
"f c #ffffff",
/* pixels */
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"fffffffffffffffffffffff......ffffffffffffffffffffffff.......fffffffffff.ffffffffffffffffffffffffffff",
"ffffffffffffffffffffff.ffccff.....fffffffffffffffffff..aaa..fffff##ffff...ffffffffffffffffffffffffff",
"ffffffffffffffffffffff.ccffccfccff.....ffffffffffffff..aaa..ffff#ffffff.ffffffffffffffffffffffffffff",
"ffffffffffffffffffffff.ffcc.....ccffcff.....fffffffff.......fffffffff...ffffffffffffffffffffffffffff",
"ffffffffffffffffffffffb..ff..fff.....ccffccf......ffffffffff##fffffff...ffffffffffffffffffffffffffff",
"ffffffffffffffffffffffb..ccff.fffffff......cffccff...fffff##ffffffffffffff##ffffffffffffffffffffffff",
"ffffffffffffffffffffffb..ffcc.ee..fffffffff.....ccf..ffff#fffffffffffff#ffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbb..ffc..fffffff..fffffff...ccff##ffffffffff####fffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbb..ccf..eefff..aa..fff..ff.ff##fffffffff###ffff...ffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbb..ffc..ffff.aaaaaa.ffffeef##fffffff####fffff..ddd..ffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbb..fcc..fff..aa..fffffff#ffcc..f##fffffffff..ddd..ffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbb..cff..eefff..fff..fffff..ff..ffffffffffffff...ffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbb...cc..ffffffffff....ffeffccff.ffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbb.ffcc..f..fffff..ffff##########ff##f##ff##f##ffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbb.ccff..effffff...ffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbb.ffcc..fffffff...fffffff..ff.ffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbbb..ffcc.ffeeffffffffffffee..f..ffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbbb..ccff.eeffff...fffffffff..c..ffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbbb..ffcc.ffff..ddd..fffffee..f..ffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffbbbbbbbbbb..ffc..ff..ddd..fffee..ffc..ffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffff.bbbbbbbbb..ccf..ffff...ffffe....ccf..ffffffffffffffffffffffffffffffffffffffff",
"fffffffffffffffffffffff..bbbbbbb..ffc..ffeef.......ffccff...ffffffffffffffffffffffffffffffffffffffff",
"fffffffffffffffffffffffff..bbbbbbb..f.......ccffccf......fffff..ffffffffffffffffffffffffffffffffffff",
"fffffffffffffffffffffffff....bbbbb..cffccffcff.....ffffff.....ff...fffffffffffffffffffffffffffffffff",
"fffffffffffffffffffffffffffff...bb..fccff.....fffff.......ccffccfcc....fffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffff..ff.....fffff.....ffccffcffccffcffccff...ffffffffffffffffffffffffff",
"fffffffffffffffffffffffffffffffffffffffff.....ffccfccffccfccffccfccffccf..ffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffff.....ffcffccffcffccffcffccffcffccff.ffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffff....fccffccfccffccfccffccfccffccfccff..fffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffff..ffcffccffcffccffcffccffcffccffcff..fffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"fffffffffffffff.......fffffff........ffffff.......fffffffffffffffffff..f..ffffffffffffffffffffffffff",
"fffffffffffffff.ffffff.ffffff.fffffffffff..fffffff.ff..ffffffffffffff..f..ffffffffffffffffffffffffff",
"fffffffffffffff.fffffff..ffff.fffffffffff..ffffffffff..ffffffffffffff..f..ffffffffffffffffffffffffff",
"fffffffffffffff.fffffff..ffff.fffffffffff..ffffffffff....fff.....ffff..f..ffff.fffffffffffffffffffff",
"fffffffffffffff.fffffff..ffff.......fffff..ffffffffff..ffffffffff..ff..f..ff..ffffffffffffffffffffff",
"fffffffffffffff.fffffff..ffff.fffffffffff..ffffffffff..fffff.......ff..f....ffffffffffffffffffffffff",
"fffffffffffffff.fffffff..ffff.fffffffffff..ffffffffff..fff..fffff..ff..f..ff..ffffffffffffffffffffff",
"fffffffffffffff.ffffff.ffffff.fffffffffff..fffffff.ff..fff..fffff..ff..f..ffff.fffffffffffffffffffff",
"fffffffffffffff.......fffffff........ffffff.......fffff..fff.......ff..f..fffff..fffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffff.....ffffffffffffffffffffffffffffffffffffffff..fffffffffffffffffffffffffffffffff",
"ffffffffffffffffff..fffff..ffffffffffffffffffffffffffffffffffffff..fffffffffffffffffffffffffffffffff",
"ffffffffffffffffff..fffffffffffffffffffffffffffffffffffffffffffff..fffffffffffffffffffffffffffffffff",
"ffffffffffffffffff..ffffffffffff.....ffff.....ff...ffff.......fff..ffff.....ffffffffffffffffffffffff",
"ffffffffffffffffffff.....ffffffffffff..ff..fff..fff..ff..fffff..f..ff..fffff..ffffffffffffffffffffff",
"fffffffffffffffffffffffff..fffff.......ff..fff..fff..ff..fffff..f..ff.........ffffffffffffffffffffff",
"fffffffffffffffffffffffff..fff..fffff..ff..fff..fff..ff..fffff..f..ff..fffffffffffffffffffffffffffff",
"ffffffffffffffffff..fffff..fff..fffff..ff..fff..fff..ff..fffff..f..ff..fffff..ffffffffffffffffffffff",
"ffffffffffffffffffff.....fffffff.......ff..fff..fff..ff.......fff..ffff.....ffffffffffffffffffffffff",
"fffffffffffffffffffffffffffffffffffffffffffffffffffffff..fffffffffffffffffffffffffffffffffffffffffff",
"fffffffffffffffffffffffffffffffffffffffffffffffffffffff..fffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"fffffffff..ffffffffffffffffffffffffffff..ff.ffffffffffffffffffffffffffff..ffffffffffffffffffffffffff",
"fffffffff..ffffffffffffffffffffffffffff..ffffffffffffffffffffffffff..fffffffffffffffffffffffffffffff",
"ffffffff.ff..ffffffffffffffffffffffffff..ffffffffffffffffffffffffff..fffffffffffffffffffffffffffffff",
"ffffffff.ff..fffff.......ffff.......fff..ff.ffff.....fffff......fff....f..ffff.....fff..ff...fffffff",
"ffffff..fffff..fff..fffff..ff.ffffff.ff..ff.ff..fffff..fffffffff.ff..fff..ff..fffff..f....fff..fffff",
"ffffff..fffff..fff..fffff..ff.ffffff.ff..ff.ff..ffffffffff.......ff..fff..ff..fffff..f..fffff..fffff",
"ffffff.........fff..fffff..ff.ffffff.ff..ff.ff..fffffffff.ffffff.ff..fff..ff..fffff..f..fffff..fffff",
"ffff..fffffffff.ff..fffff..ff.ffffff.ff..ff.ff..fffff..ff.ffffff.ff..fff..ff..fffff..f..fffff..fffff",
"ffff..fffffffff.ff.......ffff.......fff..ff.ffff.....fffff.......ffff..f..ffff.....fff..fffff..fffff",
"ffffffffffffffffff..fffffffff.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffff..fffffffff.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
};
SIMPLE  =                    T                                                  BITPIX  =                    8                                                  NAXIS   =                    2                                                  NAXIS1  =                  100                                                  NAXIS2  =                   75                                                  HISTORY Written by XV 3.10a                                                     END                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             TT             TTTTTT           TT                                                                                        TTT           TTT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       